plugins { id 'com.android.application' }

android {
    namespace 'tw.ajo.travelnotebook'
    compileSdk 35

    defaultConfig {
        applicationId 'tw.ajo.travelnotebook'
        minSdk 26
        targetSdk 34
        versionCode 120
        versionName '1.0.20'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}


dependencies {
    implementation 'com.google.android.gms:play-services-mlkit-text-recognition:19.0.1'
    implementation 'com.google.android.gms:play-services-mlkit-text-recognition-korean:16.0.1'
}
