plugins {
    id 'com.android.application'
}

android {
    namespace 'com.joyce.currencyconverter'
    compileSdk 35

    defaultConfig {
        applicationId 'com.joyce.currencyconverter'
        minSdk 24
        targetSdk 35

        def runNumber = System.getenv('GITHUB_RUN_NUMBER')
        versionCode runNumber != null ? runNumber.toInteger() : 1
        versionName runNumber != null ? "1.${runNumber}" : '1.0'
    }
}
