from pathlib import Path

p=Path('/tmp/ajo/ajo_build_min/app/src/main/assets/index.html')
s=p.read_text()

def rep(old,new,label):
    global s
    if old not in s:
        raise SystemExit('v1.0.8b patch failed: '+label)
    s=s.replace(old,new,1)

rep("t.reminders=t.reminders||[];\n    for(const p of t.passes){","""t.reminders=t.reminders||[];
    t.alternatives=t.alternatives||[];
    for(const a of t.alternatives){a.type=a.type||'其他';a.area=a.area||'';a.note=a.note||'';a.maps=a.maps||'';a.url=a.url||'';a.status=a.status||'candidate';a.scheduledDayId=a.scheduledDayId||'';a.scheduledDate=a.scheduledDate||''}
    for(const p of t.passes){""",'migrate alternatives')
rep("memo:'',reminders:[],stays:[],passes:[],days:[]","memo:'',reminders:[],alternatives:[],stays:[],passes:[],days:[]",'new trip alternatives')

style_marker='.detail-foot-actions{display:flex;gap:8px;justify-content:flex-end;flex-wrap:wrap}\n'
if style_marker not in s: raise SystemExit('v1.0.8b patch failed: style marker')
extra='''.alt-filter{display:flex;gap:6px;overflow-x:auto;padding:2px 0 9px;scrollbar-width:none}.alt-filter::-webkit-scrollbar{display:none}.alt-chip{border:0;border-radius:999px;background:#f0eee5;padding:7px 11px;white-space:nowrap;font-size:.78rem}.alt-chip.on{background:var(--yellow);color:#111}\n.alt-card{background:#fff;border:1px solid var(--line);border-left:5px solid var(--yellow);border-radius:14px;padding:10px 10px;margin-bottom:7px;box-shadow:var(--shadow)}.alt-main{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;align-items:start}.alt-title{font-size:1rem;line-height:1.35}.alt-meta{font-size:.8rem;color:var(--muted);margin-top:4px;line-height:1.45}.alt-note{font-size:.82rem;color:#555;margin-top:4px;line-height:1.45;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.alt-actions{display:flex;gap:5px;flex-wrap:wrap;justify-content:flex-end}.alt-badge{display:inline-block;border-radius:999px;padding:2px 7px;background:var(--yellow2);font-size:.68rem;margin-right:6px}.alt-status{display:inline-block;border-radius:999px;padding:2px 7px;background:#eef4ea;color:#356034;font-size:.68rem;margin-left:5px}.alt-status.visited{background:#ececec;color:#666}.alt-form-note{width:100%;min-height:75px;border:1px solid #ddd7c4;border-radius:12px;padding:11px}\n'''
s=s.replace(style_marker,style_marker+extra,1)

insert_at=s.index('function renderBig(){')
if insert_at<0: raise SystemExit('v1.0.8b patch failed: insert alt')
alt_code=r'''let altFilter='全部';
const altTypes=['餐廳','景點','購物','咖啡','其他'];
function altItemType(type){return type==='餐廳'||type==='咖啡'?'餐廳':type==='景點'?'景點':type==='購物'?'購物':'一般'}
function altStatusHtml(a){if(a.status==='visited')return '<span class="alt-status visited">已去</span>';if(a.scheduledDate)return `<span class="alt-status">已排入 ${fmtDate(a.scheduledDate)}</span>`;return''}
function setAltFilter(v){altFilter=v;renderAlt()}
function findAlt(id){for(const t of data.trips){const a=(t.alternatives||[]).find(x=>x.id===id);if(a)return {t,a}}return null}
function openAltMap(id){const f=findAlt(id);if(f)openExternalUrl(preferredMapUrl(f.a))}
async function renderAlt(){const t=currentMemoTrip();if(!t){$('#screen').innerHTML=topbar('備選地點',false)+`<main class="content"><div class="empty">請先新增一趟旅程</div></main>`;return}t.alternatives=t.alternatives||[];const list=t.alternatives.filter(a=>altFilter==='全部'||a.type===altFilter);const counts={};for(const a of list)counts[a.id]=await countAttachments(a.id);$('#screen').innerHTML=topbar('備選地點',false)+`<main class="content"><div class="trip-context">${esc(t.name)}</div><div class="alt-filter">${['全部',...altTypes].map(x=>`<button class="alt-chip ${altFilter===x?'on':''}" onclick="setAltFilter('${x}')">${x}</button>`).join('')}</div>${list.length?list.map(a=>{const mapUrl=preferredMapUrl(a);return `<div class="alt-card"><div class="alt-main"><div onclick="editAlt('${a.id}')"><div class="alt-title"><span class="alt-badge">${esc(a.type||'其他')}</span>${esc(a.title)}${altStatusHtml(a)}</div>${a.area?`<div class="alt-meta">${esc(a.area)}</div>`:''}${a.note?`<div class="alt-note">${esc(a.note)}</div>`:''}</div><div class="alt-actions">${mapUrl?`<button class="tiny yellow" onclick="openAltMap('${a.id}')">導航</button>`:''}<button class="tiny" onclick="addAltToItinerary('${a.id}')">加入行程</button>${counts[a.id]?`<button class="tiny" onclick="openAttachments('${a.id}')">附件 ${counts[a.id]}</button>`:''}</div></div></div>`}).join(''):`<div class="empty">${altFilter==='全部'?'還沒有備選地點':'這個分類目前沒有備選地點'}</div>`}</main><button class="fab" onclick="newAlt()">＋</button>`}
function altForm(a={},includeFiles=false){return `<div class="formgrid"><div class="field"><label>種類</label><select id="aType">${altTypes.map(x=>`<option ${x===(a.type||'餐廳')?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>地點／餐廳名稱</label><input id="aTitle" value="${esc(a.title||'')}" placeholder="例如：想吃的餐廳"></div><div class="field"><label>城市／區域（選填）</label><input id="aArea" value="${esc(a.area||'')}" placeholder="例如：西面／海雲台"></div><div class="field"><label>簡短備註</label><textarea class="alt-form-note" id="aNote">${esc(a.note||'')}</textarea></div><div class="field"><label>Google Maps 網址</label><input id="aMaps" value="${esc(a.maps||'')}"></div><div class="field"><label>NAVER／其他網址</label><input id="aUrl" value="${esc(a.url||'')}"></div><div class="field"><label>狀態</label><select id="aStatus"><option value="candidate" ${(a.status||'candidate')==='candidate'?'selected':''}>備選</option><option value="visited" ${a.status==='visited'?'selected':''}>已去</option></select></div>${a.scheduledDate?`<div class="subtle">目前標記：已排入 ${fmtDate(a.scheduledDate)}</div>`:''}${includeFiles?`<div class="field"><label>附件（可多選 PDF／圖片）</label><input id="aFiles" type="file" accept="application/pdf,image/*" multiple></div>`:''}</div>`}
function newAlt(){dlg('新增備選地點',altForm({},true),`<button class="secondary" onclick="closeDlg()">取消</button><button class="primary" onclick="saveNewAlt()">新增</button>`)}
async function saveNewAlt(){const t=currentMemoTrip(),title=$('#aTitle').value.trim();if(!t)return;if(!title)return appAlert('請填地點／餐廳名稱');const id=uid();const a={id,type:$('#aType').value,title,area:$('#aArea').value.trim(),note:$('#aNote').value,maps:$('#aMaps').value.trim(),url:$('#aUrl').value.trim(),status:$('#aStatus').value,scheduledDayId:'',scheduledDate:''};t.alternatives=t.alternatives||[];t.alternatives.push(a);for(const f of [...($('#aFiles')?.files||[])])await putAttachment({id:uid(),itemId:id,name:f.name,type:f.type||'application/octet-stream',blob:f,created:Date.now()});saveData();closeDlg();renderAlt()}
function editAlt(id){const f=findAlt(id);if(!f)return;dlg('編輯備選地點',altForm(f.a,true),`<button class="dangerbtn" onclick="deleteAlt('${id}')">刪除</button><button class="primary" onclick="saveAltEdit('${id}')">儲存</button>`)}
async function saveAltEdit(id){const f=findAlt(id),title=$('#aTitle').value.trim();if(!f)return;if(!title)return appAlert('請填地點／餐廳名稱');Object.assign(f.a,{type:$('#aType').value,title,area:$('#aArea').value.trim(),note:$('#aNote').value,maps:$('#aMaps').value.trim(),url:$('#aUrl').value.trim(),status:$('#aStatus').value});for(const file of [...($('#aFiles')?.files||[])])await putAttachment({id:uid(),itemId:id,name:file.name,type:file.type||'application/octet-stream',blob:file,created:Date.now()});saveData();closeDlg();renderAlt()}
function deleteAlt(id){const f=findAlt(id);if(!f)return;dlg('刪除備選地點',`<p>確定刪除「${esc(f.a.title)}」？</p><label class="checkline" style="margin-top:12px"><input id="deleteAltFiles" type="checkbox" checked> 同時刪除這筆備選的附件</label>`,`<button class="secondary" onclick="editAlt('${id}')">取消</button><button class="dangerbtn" onclick="confirmDeleteAlt('${id}')">確定刪除</button>`)}
async function confirmDeleteAlt(id){const f=findAlt(id);if(!f)return;if($('#deleteAltFiles')?.checked)await deleteAttachmentsByItem(id);f.t.alternatives=(f.t.alternatives||[]).filter(x=>x.id!==id);saveData();closeDlg();renderAlt()}
function addAltToItinerary(id){const f=findAlt(id);if(!f)return;const days=[...(f.t.days||[])].sort((a,b)=>a.date.localeCompare(b.date));if(!days.length)return appAlert('請先在旅程裡新增日期');dlg('加入行程',`<div class="formgrid"><div class="field"><label>加入哪一天</label><select id="altDay">${days.map(d=>`<option value="${d.id}">${fmtDate(d.date)}｜${esc(d.city||'')}</option>`).join('')}</select></div><div class="field"><label>時間（選填）</label><input id="altTime" class="time-input" inputmode="numeric" maxlength="5" placeholder="例如 1830" oninput="formatTimeTyping(this)"></div><div class="subtle">加入後，這筆仍會保留在「備選」裡。</div></div>`,`<button class="secondary" onclick="closeDlg()">取消</button><button class="primary" onclick="confirmAddAltToItinerary('${id}')">加入</button>`)}
async function cloneAttachmentsForItem(srcId,dstId){for(const a of await getAttachments(srcId))await putAttachment({...a,id:uid(),itemId:dstId,created:Date.now()})}
async function confirmAddAltToItinerary(id){const f=findAlt(id);if(!f)return;const d=dayById(f.t,$('#altDay').value),time=normalizeTime($('#altTime').value);if(time===null)return appAlert('時間請用 24 小時制，例如 1830 或 18:30');const iid=uid();d.items=d.items||[];d.items.push({id:iid,time,type:altItemType(f.a.type),title:f.a.title,note:f.a.note||'',maps:f.a.maps||'',url:f.a.url||''});await cloneAttachmentsForItem(f.a.id,iid);f.a.scheduledDayId=d.id;f.a.scheduledDate=d.date;saveData();closeDlg();renderAlt();appAlert(`已加入 ${fmtDate(d.date)} 行程`)}
function moveItemToAlt(iid){const t=tripById(route.tripId),d=dayById(t,route.dayId),it=d?.items.find(x=>x.id===iid);if(!it)return;const type=it.type==='餐廳'?'餐廳':it.type==='景點'?'景點':it.type==='購物'?'購物':'其他';t.alternatives=t.alternatives||[];t.alternatives.push({id:it.id,type,title:it.title,area:d.city||'',note:it.note||'',maps:it.maps||'',url:it.url||'',status:'candidate',scheduledDayId:'',scheduledDate:''});removeLinkedReminder(t,'item',iid);d.items=d.items.filter(x=>x.id!==iid);saveData();syncNativeReminders();closeDlg();renderDay();appAlert('已移到備選地點')}

'''
s=s[:insert_at]+alt_code+s[insert_at:]

rep("""dlg('編輯行程',itemForm(it,true),`<button class=\"dangerbtn\" onclick=\"deleteItem('${iid}')\">刪除行程</button><button class=\"secondary\" onclick=\"duplicateItem('${iid}')\">複製</button><button class=\"primary\" onclick=\"saveItemEdit('${iid}')\">儲存</button>`)""","""dlg('編輯行程',itemForm(it,true),`<button class=\"dangerbtn\" onclick=\"deleteItem('${iid}')\">刪除行程</button><button class=\"secondary\" onclick=\"moveItemToAlt('${iid}')\">移到備選</button><button class=\"secondary\" onclick=\"duplicateItem('${iid}')\">複製</button><button class=\"primary\" onclick=\"saveItemEdit('${iid}')\">儲存</button>`)""",'move item to alt')

p.write_text(s)
