from pathlib import Path
import re

root=Path('/tmp/ajo/ajo_build_min')
p=root/'app/src/main/assets/index.html'
s=p.read_text()

start=s.find('function guessReceiptStore(lines){')
end=s.find('function receiptOcrResult(json){', start)
if start<0 or end<0:
    raise SystemExit('v1.0.18 patch failed: receipt parser block')

new=r'''function receiptCleanStoreValue(v){let x=String(v||'').replace(/^[\s:：\-–—]+/,'').replace(/\s+/g,' ').trim();x=x.replace(/^(?:상호|매장명|매장명칭|가맹점명|사업장명|매매징명|retailer\s*name|merchant\s*name|store\s*name|name)\s*[:：]?\s*/i,'').trim();if(!x||/^(?:name|retailer|merchant|store|receipt|영수증)$/i.test(x))return'';const letters=(x.match(/[A-Za-z가-힣一-龥ぁ-んァ-ン]/g)||[]).length;if(letters<2)return'';if(/[0-9]{7,}/.test(x)&&letters<3)return'';return x.replace(/[＊*]+$/,'').trim().slice(0,50)}
function receiptStoreFromLabel(lines,from=0,to=lines.length){for(let i=from;i<Math.min(to,lines.length);i++){const line=lines[i];if(!/(상호|매장명|매장명칭|가맹점명|사업장명|매매징명|retailer\s*name|merchant\s*name|store\s*name)/i.test(line))continue;let v=receiptCleanStoreValue(line);if(v&&v!==line.trim()&&!/^(?:CubeRefund)$/i.test(v))return v;for(let j=i+1;j<=Math.min(i+2,lines.length-1);j++){v=receiptCleanStoreValue(lines[j]);if(v&&!/(주소|address|tel|전화|대표|사업자|receipt|영수증)/i.test(v)&&!/^(?:CubeRefund)$/i.test(v))return v}}return''}
function guessReceiptStore(lines){const joined=lines.join('\n');const retailerAt=lines.findIndex(x=>/(판매자\s*Retailer|판매자|retailer)/i.test(x));if(retailerAt>=0){const r=receiptStoreFromLabel(lines,retailerAt,retailerAt+9);if(r)return r}const known=[/[^\n]*올리브영[^\n]*/i,/[^\n]*메디스퀘어\s*약국[^\n]*/i,/[^\n]*ART\s*BOX[^\n]*/i,/[^\n]*아트박스[^\n]*/i,/[^\n]*이불\s*168[^\n]*/i,/[^\n]*롯데(?:백화점|\(백\))?[^\n]*/i,/[^\n]*다이소[^\n]*/i];for(const re of known){const m=joined.match(re);if(m){const v=receiptCleanStoreValue(m[0]);if(v)return v}}const labeled=receiptStoreFromLabel(lines,0,Math.min(lines.length,18));if(labeled)return labeled;const bad=/(영수증|receipt|사업자|사업장|대표|tel|전화|주소|address|card|카드|승인|거래|일시|date|time|합계|총액|결제|amount|total|vat|세액|부가세|현금|cash|수량|qty|passport|여권|refund|환급|tax|barcode|serial|no\.?\s*\d)/i;for(const line of lines.slice(0,12)){const v=receiptCleanStoreValue(line);if(!v||v.length>45||bad.test(v))continue;if((v.match(/[A-Za-z가-힣一-龥ぁ-んァ-ン]/g)||[]).length>=2)return v}return''}
function parseReceiptNumber(raw){let x=String(raw).replace(/[₩원KRW$€¥￥\s]/gi,'');if(/^[-+]?\d{1,3}(?:,\d{3})+(?:\.\d{1,2})?$/.test(x))x=x.replace(/,/g,'');else if(/^[-+]?\d+,\d{1,2}$/.test(x))x=x.replace(',','.');else x=x.replace(/,/g,'');const n=Number(x);return Number.isFinite(n)?n:0}
function receiptNumberTokens(line){return (String(line||'').match(/[-+]?\d[\d,.]*/g)||[]).map(raw=>({raw,n:parseReceiptNumber(raw),digits:raw.replace(/\D/g,'')}))}
function receiptAmountLabelScore(line,hasRefund){const x=String(line||'');if(/(Receive\s*Amount|Received\s*Amount|받은\s*금액|받을\s*금액|수취\s*금액|실\s*결제)/i.test(x))return 560;if(/(승인\s*금액|청구\s*금액|청구금액)/i.test(x))return hasRefund?550:520;if(/(신용\s*카드|credit\s*card)/i.test(x))return hasRefund?525:455;if(/(결제\s*금액|결제금액|payment\s*amount)/i.test(x))return hasRefund?390:500;if(/(Payment\s*Total|Total\s*Amount|grand\s*total|amount\s*due|판매계|총\s*금액|총액|합계\s*금액|합계)/i.test(x))return hasRefund?360:430;if(/(현금|cash)/i.test(x))return 300;if(/(소계|subtotal)/i.test(x))return 250;return 0}
function receiptIdContext(line){return /(passport|여권|카드\s*번호|card\s*(?:no|number)|승인\s*번호|승인번호|사업자|reg\.?\s*no|serial|발행번호|receipt\s*no|영수증\s*no|전화|tel|연락처|pos\s*no|거래번호|주문번호|item\s*(?:no|code)|상품\s*코드|품번|barcode|바코드)/i.test(line)}
function receiptAmountCandidates(lines,currency){const out=new Map(),hasRefund=lines.some(x=>/(tax\s*refund|택스\s*리펀드|택스리펀드|환급|refund\s*value|즉시환급)/i.test(x)),currencyRe=/(₩|원|KRW|€|EUR|\$|USD|¥|JPY|円)/i,dateRe=/(?:19|20)\d{2}\s*[-./]\s*\d{1,2}\s*[-./]\s*\d{1,2}|\b\d{1,2}:\d{2}(?::\d{2})?\b/;function add(raw,line,score,strong){const tok={raw,n:parseReceiptNumber(raw),digits:String(raw).replace(/\D/g,'')},n=tok.n;if(!(n>0))return;if(currency==='KRW'&&n<10&&!strong)return;if(/^(?:19|20)\d{5,6}$/.test(tok.digits)&&!/[,.]/.test(raw))return;if(tok.digits.length>=8&&!/[,.]/.test(raw)&&!strong)return;if(tok.digits.length>=10)return;if(!strong&&receiptIdContext(line))return;if(!strong&&dateRe.test(line))return;if(!strong&&!/[,.]/.test(raw)&&tok.digits.length>=7)return;if(currency==='KRW'&&n>50000000)return;const key=String(n),prev=out.get(key),bonus=currencyRe.test(line)?20:0,finalScore=score+bonus;if(!prev)out.set(key,{amount:n,score:finalScore,line,hits:1});else{prev.hits++;if(finalScore>prev.score){prev.score=finalScore;prev.line=line}}}
for(let i=0;i<lines.length;i++){const line=lines[i],score=receiptAmountLabelScore(line,hasRefund),refundLine=/(tax\s*refund|택스\s*리펀드|택스리펀드|환급액|refund\s*value|net\s*refund)/i.test(line),taxLine=/(V\.?A\.?T|부가세|세액|taxable|과세)/i.test(line),idLine=receiptIdContext(line);if(score>0&&!refundLine&&!taxLine&&!idLine){const ts=receiptNumberTokens(line);for(const t of ts)add(t.raw,line,score,true);if(!ts.length&&i+1<lines.length&&/^[\s₩원KRW€EUR$USD¥JPY円+\-\d,.]+$/i.test(lines[i+1]))for(const t of receiptNumberTokens(lines[i+1]))add(t.raw,line+' '+lines[i+1],score-10,true)}if(score===0&&!refundLine&&!taxLine&&!idLine&&!dateRe.test(line)){for(const t of receiptNumberTokens(line)){const formatted=/,\d{3}(?:\D|$)/.test(t.raw),withCurrency=currencyRe.test(line);if(formatted||withCurrency)add(t.raw,line,formatted?80:65,false)}}}
let a=[...out.values()];for(const x of a)x.score+=Math.min(35,(x.hits-1)*12);a.sort((x,y)=>y.score-x.score||y.hits-x.hits||y.amount-x.amount);return a.slice(0,3)}
function guessReceiptCategory(text){const x=String(text||'').toLowerCase();if(/호텔|hotel|hostel|숙박|motel|airbnb/.test(x))return'住宿';if(/택시|taxi|\bbus\b|버스|지하철|metro|subway|korail|기차|\btrain\b|\\buber\\b|交通/.test(x))return'交通';if(/입장|ticket|museum|aquarium|spa|스파|찜질|마사지|massage|tour|activity/.test(x))return'門票／活動';if(/약국|pharmacy|drugstore|마트|mart|백화점|department|올리브영|olive\s*young|다이소|daiso|아트박스|art\s*box|롯데|이불|침구|화장품|크림|마스크|편의점|7[\s-]*eleven|세븐|gs25|\bcu\b|\bshop\b|\bstore\b/.test(x))return'購物';if(/식당|restaurant|cafe|카페|커피|coffee|치킨|닭|burger|pizza|food|meal|bbq|고기|국밥|빵|bakery|dessert|디저트/.test(x)){const h=new Date().getHours();if(h>=5&&h<11)return'早餐';if(h>=11&&h<16)return'午餐';if(h>=16&&h<23)return'晚餐';return'其他吃的'}return'其他'}
'''
s=s[:start]+new+s[end:]
p.write_text(s)

p=root/'app/build.gradle'
g=p.read_text()
g=re.sub(r"versionCode\s+\d+","versionCode 118",g,count=1)
g=re.sub(r"versionName\s+['\"][^'\"]+['\"]","versionName '1.0.18'",g,count=1)
p.write_text(g)
